// Sample data for the deliveries demo. Neutral, made-up companies and places.

export const deliveries = [
  {
    id: "2041",
    from: "Rotterdam",
    fc: "NL",
    to: "Antwerp",
    tc: "BE",
    company: "Northwind Logistics",
    date: "Sep 27",
    status: "scheduled",
    label: "Scheduled",
    meta: "Pickup at 08:30",
    stage: 0,
    cargo: "Flat-pack furniture, 18 pallets",
    weight: "9,800 kg",
    vehicle: "Box truck, 18 t",
    stops: [
      ["08:30", "Pickup", "Rotterdam, Maasvlakte"],
      ["10:10", "Delivery", "Antwerp, Kallo"],
    ],
  },
  {
    id: "2042",
    from: "Lyon",
    fc: "FR",
    to: "Milan",
    tc: "IT",
    company: "Bellweather Foods",
    date: "Sep 27",
    status: "transit",
    label: "In transit",
    meta: "2 of 3 stops done",
    stage: 2,
    cargo: "Chilled dairy, 22 pallets",
    weight: "14,200 kg",
    vehicle: "Reefer trailer",
    stops: [
      ["06:00", "Pickup", "Lyon, Corbas"],
      ["11:40", "Customs", "Fréjus tunnel"],
      ["15:20", "Delivery", "Milan, Lacchiarella"],
    ],
  },
  {
    id: "2043",
    from: "Hamburg",
    fc: "DE",
    to: "Copenhagen",
    tc: "DK",
    company: "Fjord Freight",
    date: "Sep 26",
    status: "delivered",
    label: "Delivered",
    meta: "Signed by M. Holm",
    stage: 3,
    cargo: "Bicycle parts, 12 pallets",
    weight: "6,100 kg",
    vehicle: "Curtainsider",
    stops: [
      ["07:15", "Pickup", "Hamburg, Billbrook"],
      ["13:05", "Delivery", "Copenhagen, Nordhavn"],
    ],
  },
  {
    id: "2044",
    from: "Saint-Jean-de-Luz",
    fc: "FR",
    to: "Frankfurt am Main",
    tc: "DE",
    company: "Compagnie Générale de Transports et d'Entreposage du Sud-Ouest",
    date: "Sep 26",
    status: "delayed",
    label: "Delayed",
    meta: "Waiting at the border",
    stage: 2,
    cargo: "Canned fish, 30 pallets",
    weight: "21,400 kg",
    vehicle: "Tautliner, 40 t",
    stops: [
      ["05:30", "Pickup", "Saint-Jean-de-Luz, port"],
      ["12:50", "Border", "Strasbourg, Pont de l'Europe"],
      ["18:30", "Delivery", "Frankfurt, Osthafen"],
    ],
  },
  {
    id: "2045",
    from: "Porto",
    fc: "PT",
    to: "Madrid",
    tc: "ES",
    company: "Atlântico Cargo",
    date: "Sep 25",
    status: "transit",
    label: "In transit",
    meta: "ETA 16:45",
    stage: 2,
    cargo: "Cork stoppers, 8 pallets",
    weight: "3,200 kg",
    vehicle: "Van, 3.5 t",
    stops: [
      ["07:00", "Pickup", "Porto, Leixões"],
      ["16:45", "Delivery", "Madrid, Coslada"],
    ],
  },
  {
    id: "2046",
    from: "Vienna",
    fc: "AT",
    to: "Prague",
    tc: "CZ",
    company: "Danube Parcel Co.",
    date: "Sep 25",
    status: "scheduled",
    label: "Scheduled",
    meta: "Pickup at 14:00",
    stage: 0,
    cargo: "Printed books, 6 pallets",
    weight: "4,900 kg",
    vehicle: "Box truck, 12 t",
    stops: [
      ["14:00", "Pickup", "Vienna, Inzersdorf"],
      ["18:20", "Delivery", "Prague, Hostivař"],
    ],
  },
  {
    id: "2047",
    from: "Oslo",
    fc: "NO",
    to: "Gothenburg",
    tc: "SE",
    company: "Skagerrak Shipping",
    date: "Sep 24",
    status: "delivered",
    label: "Delivered",
    meta: "Signed by A. Berg",
    stage: 3,
    cargo: "Salmon feed, 20 pallets",
    weight: "18,000 kg",
    vehicle: "Curtainsider",
    stops: [
      ["06:40", "Pickup", "Oslo, Sjursøya"],
      ["10:55", "Delivery", "Gothenburg, Arendal"],
    ],
  },
  {
    id: "2048",
    from: "Zurich",
    fc: "CH",
    to: "Munich",
    tc: "DE",
    company: "Alpine Express",
    date: "Sep 24",
    status: "transit",
    label: "In transit",
    meta: "1 of 2 stops done",
    stage: 1,
    cargo: "Watch components, 2 pallets",
    weight: "450 kg",
    vehicle: "Van, 3.5 t",
    stops: [
      ["09:00", "Pickup", "Zurich, Altstetten"],
      ["13:30", "Delivery", "Munich, Riem"],
    ],
  },
  {
    id: "2049",
    from: "Barcelona",
    fc: "ES",
    to: "Marseille",
    tc: "FR",
    company: "Costa Brava Transports",
    date: "Sep 23",
    status: "scheduled",
    label: "Scheduled",
    meta: "Pickup at 07:45",
    stage: 0,
    cargo: "Olive oil, 16 pallets",
    weight: "15,600 kg",
    vehicle: "Tautliner, 40 t",
    stops: [
      ["07:45", "Pickup", "Barcelona, Zona Franca"],
      ["13:15", "Delivery", "Marseille, Arenc"],
    ],
  },
  {
    id: "2050",
    from: "Dublin",
    fc: "IE",
    to: "Manchester",
    tc: "GB",
    company: "Liffey Line",
    date: "Sep 23",
    status: "delivered",
    label: "Delivered",
    meta: "Signed by R. Doyle",
    stage: 3,
    cargo: "Whiskey casks, 10 pallets",
    weight: "7,300 kg",
    vehicle: "Box truck, 18 t",
    stops: [
      ["05:50", "Pickup", "Dublin Port"],
      ["14:10", "Delivery", "Manchester, Trafford Park"],
    ],
  },
];

export const stages = ["Booked", "Picked up", "In transit", "Delivered"];

export const findDelivery = (id) => deliveries.find((d) => d.id === id);
